{
    "name": "Multi-Activity Operations",
    "version": "18.0.1.0.0",
    "category": "Services",
    "summary": "Cash close, expenses, audit, POS and stock hooks",
    "license": "LGPL-3",
    "depends": [
        "multi_activity_security",
        "point_of_sale",
        "stock",
        "product",
        "purchase",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ir_sequence.xml",
        "data/expense_category_data.xml",
        "data/ir_cron.xml",
        "views/expense_views.xml",
        "views/audit_views.xml",
        "views/alert_views.xml",
        "views/product_views.xml",
        "views/pos_config_views.xml",
        "views/pos_config_list_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
}
