from . import business_type
from . import establishment
from . import mixin
from . import res_users
from . import res_company
from . import pos_config
from . import stock_warehouse
from . import product_template
from . import hr_employee
from . import res_lang
from . import res_config_settings
from . import ir_http
